### ISSUE TITLE
Monitor doesn't display miner hashrate / pool stats on nodejs-cryptonote-pool

### ISSUE THREAD

**Issue by funkypenguin** [turtlecoin/ios-pool-monitor#34]
Hey @derp-derp-derp,

I recently upgraded https://trtl.heigh-ho.funkypenguin.co.nz from https://github.com/turtlecoin/turtle-pool to https://github.com/dvandal/cryptonote-nodejs-pool (which seems to be a derivative of forknote-pool), and my pool no longer works (entirely) in the app.

1. On the "Dashboard" tab, all the miner stats work aside for hashrate (the first value), and the hashrate graph.
2. The "Pool" tab flashes the turtlecoin logo continiously, and never displays anything else.
3. The "Payouts" tab works as expected.

My API is https://api.trtl.heigh-ho.funkypenguin.co.nz, and a working API is http://turtle.imhard4.men:8117

Happy to help with debug, or with adjustments to the cryptonote-nodejs-pool  API if required :)

D

**Comment by derp-derp-derp** [comment]
Confirming receipt for now - thank you!

**Comment by funkypenguin** [comment]
So I compared the output of stats_address on my pool (not working) to us.turtlepool.space (working), and the only difference I can see is:

# Working
```
   "stats":{  
      "hashes":"9231768637",
      "lastShare":"1533199555",
      "balance":"79613",
      "paid":"123072000",
      "hashrate":"417.00 H"
   },
```

# Non-working

```
   "stats":{  
      "hashes":"66446829033",
      "lastShare":"1533199455",
      "balance":"44367",
      "paid":"620040900",
      "minPayoutLevel":"100000",
      "hashrate":483,
      "roundScore":290000,
      "roundHashes":290000,
      "hashrate_1h":0,
      "hashrate_6h":0,
      "hashrate_24h":0
   },
```
Could the issue have to do with the formatting of the hashrate?

**Comment by funkypenguin** [comment]
I also compared <api>/live_stats, and noticed only that the "config" section on the non-working API includes a lot of details not present on the working API, i.e.:

```
"config":{  
      "poolHost":"trtl.heigh-ho.funkypenguin.co.nz",
      "ports":[  ],
      "cnAlgorithm":"cryptonight_light",
      "cnVariant":1,
      "cnBlobType":2,
      "hashrateWindow":600,
      "fee":0.0987654321,
      "networkFee":0,
      "coin":"turtlecoin",
      "coinUnits":100,
      "coinDecimalPlaces":2,
      "coinDifficultyTarget":30,
      "symbol":"TRTL",
      "depth":40,
      "donation":{  

      },
      "version":"v1.3.5",
      "paymentsInterval":120,
      "minPaymentThreshold":100000,
      "maxPaymentThreshold":null,
      "transferFee":100,
      "denominationUnit":100,
      "slushMiningEnabled":false,
      "weight":300,
      "priceSource":"tradeogre",
      "priceCurrency":"NZD",
      "paymentIdSeparator":"+",
      "fixedDiffEnabled":true,
      "fixedDiffSeparator":".",
      "sendEmails":true,
      "blocksChartEnabled":true,
      "blocksChartDays":30,
      "telegramBotName":"HeighHoTRTLBot",
      "telegramBotStats":"/stats",
      "telegramBotReport":"/report",
      "telegramBotNotify":"/notify",
      "telegramBotBlocks":"/blocks"
   },
```

**Comment by derp-derp-derp** [comment]
Confirming receipt for now - thank you!
